config/routes.rb
Rails.application.routes.draw do
  resources :microblogs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/microblog.rb
class Microblog < ActiveRecord::Base
  belongs_to :user
  validates :content, length: {maximum: 140}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microblogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/microblogs_controller.rb
class MicroblogsController < ApplicationController
  before_action :set_microblog, only: [:show, :edit, :update, :destroy]

  # GET /microblogs
  # GET /microblogs.json
  def index
    @microblogs = Microblog.all
  end

  # GET /microblogs/1
  # GET /microblogs/1.json
  def show
  end

  # GET /microblogs/new
  def new
    @microblog = Microblog.new
  end

  # GET /microblogs/1/edit
  def edit
  end

  # POST /microblogs
  # POST /microblogs.json
  def create
    @microblog = Microblog.new(microblog_params)

    respond_to do |format|
      if @microblog.save
        format.html { redirect_to @microblog, notice: 'Microblog was successfully created.' }
        format.json { render :show, status: :created, location: @microblog }
      else
        format.html { render :new }
        format.json { render json: @microblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microblogs/1
  # PATCH/PUT /microblogs/1.json
  def update
    respond_to do |format|
      if @microblog.update(microblog_params)
        format.html { redirect_to @microblog, notice: 'Microblog was successfully updated.' }
        format.json { render :show, status: :ok, location: @microblog }
      else
        format.html { render :edit }
        format.json { render json: @microblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microblogs/1
  # DELETE /microblogs/1.json
  def destroy
    @microblog.destroy
    respond_to do |format|
      format.html { redirect_to microblogs_url, notice: 'Microblog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_microblog
      @microblog = Microblog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def microblog_params
      params.require(:microblog).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microblogs_helper.rb
module MicroblogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microblogs/_form.html.erb
<%= form_for(microblog) do |f| %>
  <% if microblog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(microblog.errors.count, "error") %> prohibited this microblog from being saved:</h2>

      <ul>
      <% microblog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microblogs/edit.html.erb
<h1>Editing Microblog</h1>

<%= render 'form', microblog: @microblog %>

<%= link_to 'Show', @microblog %> |
<%= link_to 'Back', microblogs_path %>

app/views/microblogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>AVenger Blog</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microblogs.each do |microblog| %>
      <tr>
        <td><%= microblog.content %></td>
        <td><%= microblog.user_id %></td>
        <td><%= link_to 'Show', microblog %></td>
        <td><%= link_to 'Edit', edit_microblog_path(microblog) %></td>
        <td><%= link_to 'Destroy', microblog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Microblog', new_microblog_path %>

app/views/microblogs/new.html.erb
<h1>New Microblog</h1>

<%= render 'form', microblog: @microblog %>

<%= link_to 'Back', microblogs_path %>

app/views/microblogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @microblog.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @microblog.user_id %>
</p>

<%= link_to 'Edit', edit_microblog_path(@microblog) %> |
<%= link_to 'Back', microblogs_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>CONFIDENTIAL LIST OF AVENGERS index.html.erb file</h1>

<table>
  <thead>
    <tr>
      <th>Avenger Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avenger', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>